version: "3.9"

services:
  djangoapp:
    container_name: djangoapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_DRIVER=django.db.backends.postgresql
      - PG_USER=admin
      - PG_PASSWORD=admin
      - PG_DB=cinema
      - PG_HOST=db
      - PG_PORT=5432
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=admin
      - RABBITMQ_HOST=rabbitmq # Додаємо змінну для підключення до RabbitMQ
    depends_on:
      - db
      - mongo
      - rabbitmq # Додаємо залежність від RabbitMQ

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cinema
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initial_data.json:/app/initial_data.json

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=cinema
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=root
    volumes:
      - ./initial_data.json:/docker-entrypoint-initdb.d/initial_data.json
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672" # порт для доступу до веб-інтерфейсу RabbitMQ
      - "5672:5672" # стандартний порт для підключення до RabbitMQ

  consumer:
    build:
      context: .
      dockerfile: services/Dockerfile
    container_name: consumer
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pgdata: {}
